let zh = {
    MY_LESSONS: '我的课程',
    RECOMMEND: '推荐课程',
    FREE:      '免费试听',
    POPULAR_LESSON: '热门推荐',
    SEE_MORE:    '更多',
    BUY_SINGLE_LESSON: '单课购买',
    BUNDLE:      '全部购买',
    LESSON_DETAIL: '课程详情',
    BUY_LESSONS: '选择购买方式',
    CANCEL:      '取消',
    PAYMENT:     '支付',
    CREDIT_CARD: '信用卡',
    SINGLE_LESSON: '单节课程',
    ALL_REMAINING_LESSON: '全部剩余课程',
    IOS_WARNING: 'HT English课程暂未在iOS系统内开放',
    NETWORK_FAILS: '网络出错啦',//
    PAYMENT_SUCCESSFUL: '支付成功',
	PAYMENT_FAILED: '支付失败',
}
let en = {
	MY_LESSONS: 'My lessons',
    RECOMMEND: 'Recommended',
    FREE:      'Free',
    POPULAR_LESSON: 'Popular lessons',
    SEE_MORE:    'See more',
    BUY_SINGLE_LESSON: 'Single lesson',
    BUNDLE:      'Bundle',
    LESSON_DETAIL: 'Lesson',
    BUY_LESSONS: 'Buy lessons',
    CANCEL:      'Cancel',
    PAYMENT:     'Payment',
    CREDIT_CARD: 'Credit card',
    SINGLE_LESSON: 'a single lesson',
    ALL_REMAINING_LESSON: 'all remaining lessons',
    IOS_WARNING: 'HT English is not yet available on iOS.',
    NETWORK_FAILS: 'Network Error',//
    PAYMENT_SUCCESSFUL: 'Payment Successful',
	PAYMENT_FAILED: 'Payment Failed',
}
let pt = { // 葡萄牙语
    MY_LESSONS: 'Minhas aulas',
    RECOMMEND: 'Recomendadas',
    FREE:      'Grátis',
    POPULAR_LESSON: 'Aulas populares',
    SEE_MORE:    'Ver mais',
    BUY_SINGLE_LESSON: 'Aula única',
    BUNDLE:      'Pacote',
    LESSON_DETAIL: 'Aula',
    BUY_LESSONS: 'Comprar aulas',
    CANCEL:      'Cancelar',
    PAYMENT:     'Forma de pagamento',
    CREDIT_CARD: 'Cartão de crédito',
    SINGLE_LESSON: 'Uma única aula',
    ALL_REMAINING_LESSON: 'Todas as aulas restantes',
    IOS_WARNING: 'HT English ainda não está disponível para iOS.',
    NETWORK_FAILS: 'Network Error',//
    PAYMENT_SUCCESSFUL: 'Pagamento bem sucedido',
	PAYMENT_FAILED: 'Falha de pagamento',
}
let tr = { // 土耳其语
    MY_LESSONS: 'Derslerim',
    RECOMMEND: 'Önerilen',
    FREE:      'Ücretsiz',
    POPULAR_LESSON: 'Popüler dersler',
    SEE_MORE:    'Daha fazlasına bakın',
    BUY_SINGLE_LESSON: 'Tek ders',
    BUNDLE:      'Paket',
    LESSON_DETAIL: 'Ders',
    BUY_LESSONS: 'Dersler satın alın',
    CANCEL:      'İptal',
    PAYMENT:     'ödeme',
    CREDIT_CARD: 'Kredi Kartı',
    SINGLE_LESSON: 'Tek kişilik ders',
    ALL_REMAINING_LESSON: 'Arda kalan dersler',
    IOS_WARNING: 'HT İngilizce İOS da henüz mevcut değildir.',
    NETWORK_FAILS: 'Network Error',//
    PAYMENT_SUCCESSFUL: 'Ödeme başarılı',
	PAYMENT_FAILED: 'Ödeme başarısız',
}
let ja = { // 日语
    MY_LESSONS: 'マイレッスン',
    RECOMMEND: 'おすすめ',
    FREE:      '無料',
    POPULAR_LESSON: '人気レッスン',
    SEE_MORE:    'もっと見る',
    BUY_SINGLE_LESSON: '一回のレッスンを購入する',
    BUNDLE:      '一括購買',
    LESSON_DETAIL: 'レッスン',
    BUY_LESSONS: 'レッスンを購入する',
    CANCEL:      '取り消し',
    PAYMENT:     'お支払い',
    CREDIT_CARD: 'クレジットカード',
    SINGLE_LESSON: '一回のレッスン',
    ALL_REMAINING_LESSON: '残りのレッスン',
    IOS_WARNING: 'HTEnglishはiOSは現在対応しておりません。',
    NETWORK_FAILS: 'Network Error',//
    PAYMENT_SUCCESSFUL: '支払いが成功しました',
	PAYMENT_FAILED: '支払いが失敗しました',
}
export default {
    zh_CN: zh,
    'zh-CN': zh,
	en: en,
    'zh-Hans': zh,
    pt: pt,
    tr: tr,
    ja: ja
};